seed: 420

experiment_name: "finetune_dtd"
experiment_class: FinetuneResnet
dataset: dtd
resize: 224

n_epochs: 180
batch_size: 64

optim_name: sgd
learning_rate: 0.01
weight_decay: 0
momentum: 0

model_name: resnet
model_size: 50
