seed: 420

experiment_name: None
experiment_class: FinetuneResnet
dataset: None
resize: 224

n_epochs: 30
batch_size: 128

optim_name: sgd
learning_rate: None
weight_decay: None
momentum: None

model_name: resnet
model_size: 50
